### ISSUE TITLE
Heroku: config aren't using env variables

### ISSUE THREAD

**Issue by dnbard** [dnbard/eclipse-server#101]
```
{
    "name": "eclipse",
    "hostname": "2a4c40de-e643-4925-980a-c834f174f9b0",
    "pid": 4,
    "widget_type": "httpServer",
    "level": 60,
    "err": {
        "message": "failed to connect to server [127.0.0.1:27017] on first connect",
        "name": "MongoError",
        "stack": "MongoError: failed to connect to server [127.0.0.1:27017] on first connect\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:271:12)\n    at Connection.g (events.js:291:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:165:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1281:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)"
    },
    "msg": "failed to connect to server [127.0.0.1:27017] on first connect",
    "time": "2016-11-14T09:56:54.460Z",
    "v": 0
}
```

**Comment by dnbard** [comment]
Fixed by changing of ENV var for Heroku
