### ISSUE TITLE
Invalid arguments: all arguments should be a numbers

### ISSUE THREAD

**Issue by dnbard** [dnbard/eclipse-server#66]
```
2016-10-27T12:07:10.484952+00:00 app[web.1]: /app/physics/angle.js:6
2016-10-27T12:07:10.484973+00:00 app[web.1]:             throw new TypeError(
2016-10-27T12:07:10.484974+00:00 app[web.1]:             ^
2016-10-27T12:07:10.484975+00:00 app[web.1]:
2016-10-27T12:07:10.484976+00:00 app[web.1]: TypeError: Invalid arguments: all arguments should be a numbers
2016-10-27T12:07:10.484977+00:00 app[web.1]:     at Object.exports.getAngleBetweenTwoPoints (/app/physics/angle.js:6:19)
2016-10-27T12:07:10.484978+00:00 app[web.1]:     at ActorIterator (/app/core/updateLoop.js:57:28)
2016-10-27T12:07:10.484978+00:00 app[web.1]:     at Player.actions.defaultPlayer [as onUpdate] (/app/models/player.js:58:33)
2016-10-27T12:07:10.484979+00:00 app[web.1]:     at Array.forEach (native)
2016-10-27T12:07:10.484980+00:00 app[web.1]:     at Timeout.LoopIterator [as _onTimeout] (/app/core/updateLoop.js:35:16)
2016-10-27T12:07:10.484980+00:00 app[web.1]:     at tryOnTimeout (timers.js:224:11)
2016-10-27T12:07:10.484981+00:00 app[web.1]:     at Timer.listOnTimeout (timers.js:198:5)
2016-10-27T12:07:10.639988+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by dnbard** [comment]
not repro after 	bf15084
